# Generated by Django 5.1.7 on 2025-03-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo', models.CharField(default='Fondo principal', max_length=100)),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='fondos/')),
            ],
        ),
    ]
