# Generated by Django 5.1.7 on 2025-04-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_perfilusuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
