# Generated by Django 5.1.7 on 2025-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_perfilusuario_puede_comentar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(upload_to='cabra/')),
                ('biografia', models.TextField()),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
